---

- name: Check Kubernetes version
  shell: kubectl version | grep Client | grep -oP 'v.*'
  register: check_kubernetes_version

- fail:
    msg: "Cannot get Kubernetes version"
  when: check_kubernetes_version is undefined and check_kubernetes_version.stdout is undefined

- name: Download Kubernetes images
  shell: |
    kubeadm config images list --kubernetes-version {{ check_kubernetes_version.stdout }} | xargs -L1 docker pull

- name: Create kubeadm config file
  template:
    src: kubeadm.yml
    dest: "{{ template_folder }}/kubeadm.yml"

- name: Start kubernetes
  command:
    cmd: kubeadm init --config={{ template_folder }}/kubeadm.yml
  register: kubeadm_stat

- debug:
    msg: "{{ kubeadm_stat.stdout_lines }}"
  when: kubeadm_stat is defined and kubeadm_stat.stdout | length > 0

- name: Create .kube directory
  file:
    path: "/root/.kube"
    state: directory
    mode: "1777"

- name: Setup kube config
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    mode: "600"

- name: Sleep 3 minutes
  wait_for:
    timeout: 180

- name: Untaint node
  command: kubectl taint nodes --all node-role.kubernetes.io/master-

- name: Create calico file
  template:
    src: calico.yml
    dest: "{{ template_folder }}/calico.yml"

- name: Install calico
  command: kubectl apply -f {{ template_folder }}/calico.yml

- name: Sleep 3 minutes
  wait_for:
    timeout: 180
