apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: myresume
  name: myresume
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: myresume
  template:
    metadata:
      labels:
        app.kubernetes.io/name: myresume
    spec:
      containers:
      - name: myresume
        image: {{ image_name }}:{{ image_verion }}
        ports:
        - containerPort: {{ container_port }}