apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: {{ public_ip }}
  bindPort: 6443
nodeRegistration:
  criSocket:  unix:///run/cri-dockerd.sock
  name: master-node
  taints:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
---
apiServer:
  timeoutForControlPlane: 10m0s
  extraArgs:
    authorization-mode: Node,RBAC
    service-node-port-range: 4000-32767 # important for callhome on port 4335
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kind: ClusterConfiguration
#kubernetesVersion: v{{ kubernetes_version }}
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
  podSubnet: 192.168.0.0/16