# Generated by Django 4.1 on 2022-09-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0002_alter_detailtechnical_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='image',
            field=models.ImageField(null=True, upload_to='resume-images'),
        ),
    ]
