# Generated by Django 4.1 on 2022-09-03 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0003_resume_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resume-image')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresume.resume')),
            ],
        ),
    ]
