# Generated by Django 4.1 on 2022-09-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0004_otherimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CompaniesWorked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_exp', models.PositiveIntegerField(default=0)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresume.company')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresume.resume')),
            ],
        ),
    ]
