# Generated by Django 4.1 on 2022-09-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0005_company_companiesworked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companiesworked',
            name='company_exp',
            field=models.FloatField(default=0),
        ),
    ]
