# Generated by Django 4.1 on 2022-09-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0012_alter_technical_options_company_company_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='part_project',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
