# Generated by Django 4.1 on 2022-09-03 12:44
import os

from django.db import migrations, models
import django.db.models.deletion

from myapp.settings import BASE_DIR


def InsertData():
    sqlStatement = open(os.path.join(BASE_DIR, 'query/data.sql'), 'r').read()
    return sqlStatement


class Migration(migrations.Migration):
    dependencies = [
        ('myresume', '0014_resume_gpa_resume_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_des', models.CharField(max_length=50)),
                ('project_image', models.ImageField(upload_to='resume-image')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myresume.resume')),
            ],
        ),
        migrations.RunSQL(InsertData())
    ]
