# Generated by Django 4.1 on 2022-09-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0015_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='linked',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
