# Generated by Django 4.1 on 2022-09-03 13:21
import os.path

from django.db import migrations, models

from myapp.settings import BASE_DIR


def InsertTemplate():
    sqlStatement = open(os.path.join(BASE_DIR, 'query/technical.sql'), 'r').read()
    return sqlStatement


class Migration(migrations.Migration):
    dependencies = [
        ('myresume', '0015_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='linked',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RunSQL(InsertTemplate())
    ]
