# Generated by Django 4.1 on 2024-01-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myresume', '0016_resume_linked'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMyresume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=200)),
                ('your_email', models.TextField(null=True)),
                ('email_subject', models.CharField(max_length=200, null=True)),
                ('email_description', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
